### ISSUE TITLE
pytarallo integration

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/peracotta#104]
Use pytarallo to do the upload.

Make a function that takes a path to a JSON file ready to upload (already without human_readable features) and API key (parameter, .env file like in pytarallo tests, etc...) and tarallo URL (or use .env again, to select production or dev tarallo). Return... something that tells if the upload succeeded or failed, and why (if provided).

Then enhance the function: it should read products from tarallo and delete the duplicate ones before upload. Maybe make a separate function for this, and call it.

Then enhance the GUI to call that last function and show duplicate products and features that differ. Users should be allowed to set a variant (and edit brand and model while we're at it) to make it different, if they think it is actually a different product. This should also modify brand and model and variant in the items, so they they don't get unlinked.

**Comment by e-caste** [comment]
TODO 
- GUI side
  - move back button to top left
  - move 3 other buttons to bottom center
  - add bulk identifier text input to dialog
  - add overwrite checkbox to dialog
- backend side
  - call `Tarallo.bulk_add()` and check if it works

**Comment by lvps** [comment]
The bottom part should be split in two parts, to group the buttons:

![the GUI](https://user-images.githubusercontent.com/16715831/114911284-26610780-9e1f-11eb-8439-94264b58bf17.png)

Manual and Automatic are titles or QLabels or anything that makes sense.

Also todo: use t_url to build the URLs that are opened in a browser

**Comment by e-caste** [comment]
Note: it is important that both in the GUI and in the CLI we catch **all** possible issues (e.g. no Internet connection) and errors (e.g. 500 internal server error), and that we handle them in a consistent way across the board.  

For example, we do a `bulk_add`, and we get error 500: we should prompt the user to retry uploading the PC data.
Or, there is no connection available at the moment: tell the user, and advise them to connect the PC to the Internet.  

You can check all possible errors and exceptions by looking at the pytarallo code of the method in use, and by looking at the possible exceptions that the `requests` method (e.g. `post`) called inside the pytarallo method can raise.
