### ISSUE TITLE
Case is missing type

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/peracotta#121]
Maybe not always, but they do.
Unrelated to #117, it happened before that one was implemented.

**Comment by e-caste** [comment]
Use a copy of the JSON in the GUI to prevent `pop` corrupting the JSON to upload.  
@mikeus9908 any other comments?

**Comment by mikeus9908** [comment]
the system_info variable should be used only for gui purposes. The copy of the json shouldn't be modified: just print it in the "go to Json" section and for the upload.
