### ISSUE TITLE
Ask for owner

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/peracotta#129]
Both in GUI and command line, ask `Who is the owner of this pc? (e.g. DISAT, Area IT, ...)`.
Then, after the parsing stage (this data cannot be detected by parsers, it's pointless to modify each one of them to add it), take every single **item** that has been detected and add an `owner` feature with the user-supplied value.
This will save a lot of repeated typing.

An interesting enhancement would be to query the tarallo for most common values and show them (but leaving the possibility to manually type a new value). However, the API to do that doesn't exist yet.

**Comment by il-palmi** [comment]
Already done
