### ISSUE TITLE
Get correct VRAM size

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/peracotta#13]
`lspci` isn't reliable for any graphics card made in the last 10-15 years. We didn't notice because most of our stuff is older, but still...

Some suggestions: https://www.cyberciti.biz/faq/howto-find-linux-vga-video-card-ram/

`glxinfo` from the `mesa-demos` package looks promising but needs some further investigation. Xorg logs contain no information about VRAM on my computer.

Similar question: https://askubuntu.com/q/46197 complete with people calling out the asker in the comments because they think he's lying and lspci is perfect, and suggesting that it's a duplicate of a question about RAM (not VRAM). Classy.  
Anyway, there's an answer suggesting other stuff to grep in dmesg.

**Comment by e-caste** [comment]
glxinfo works most of the time, if not: get "Video memory" value and tell the user to correct manually (it may be near the actual value, e.g. 1013MB for a 1024MB VRAM), if not: default to -1, tell the user to fix value manually.

If this solution works for you, you can close the issue.

**Comment by lvps** [comment]
@e-caste Yeha, looks good.

Should we make -1 the standard "invalid" value for ints and "?" for features?

**Comment by e-caste** [comment]
@lvps I’m keeping -1 for ints by default and setting them to None when the user doesn’t necessarily enter a value, and a default empty string “” for string values. If a feature can’t be found we won’t add it to the final dict this way

**Comment by e-caste** [comment]
@lvps also check my last commit to understand why this is needed

**Comment by lvps** [comment]
@e-caste Makes sense, all those values should be rejected by the tarallo so there's no risk of adding them accidentally
