### ISSUE TITLE
Recognize different names for the same brand and overwrite with a choosen one

### ISSUE THREAD

**Issue by il-palmi** [WEEE-Open/peracotta#131]
In some products, the brand name is fully reported (like MSI --> MICRO STAR INTERNATIONAL) and it can create ambiguity when the product is inventoried. It can be "resolved" by making a dictionary like:
MICRO STAR INTERNATIONAL: MSI
AsusTek: Asus
...
In this way also the TARALLO can find products that already exist instead of asking to the user to create a new product with a wrong brand name.

**Comment by lvps** [comment]
@ThePalm99 The famous normalization asd

**Comment by lvps** [comment]
Will be done soon (?) in https://github.com/WEEE-Open/tarallo/issues/69 even for json uploads, no need to do it here
