### ISSUE TITLE
Make all "parsers" runnable without user interaction

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/peracotta#15]
After #14 is done, we will have a bunch of functions or class methods that get a command output as input (e.g. the entire lscpu output as a string, or a filename with lscpu output) and return a dict or whatever.

These "parser" functions should run without user interaction, e.g. they shouldn't ask "Does this system have a dedicated video card?" and expect an answer. Instead, use that as a parameter, e.g.

```python
def read_lspci_-v(lspci_output: str, is_dedicated: bool):
```

The question should still be asked, but in the main/caller script, `peracotta.py`. Why, if the end result is the same? Well, we could add a command line option to the caller script that provides the needed values and feed them to the parsers, completely removing user interaction: that's the ultimate goal...

**Comment by e-caste** [comment]
The parsers are now runnable without user interaction when launched from the GUI. Some of them require a small confirmation when launched standalone for testing purposes.

Feel free to reopen the issue in case there has been a misunderstanding.
