### ISSUE TITLE
add checkbox for each line of the output to select attributes to upload to TARALLO database

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#25]
This would give the user the chance to ignore certain features that may have been wrongly detected by the script. 

This is not an urgent issue.

**Comment by lvps** [comment]
I fear that this may hurt our sanity... anyway, my plan is to add another step in the tarallo to edit all the items in the editor (the same as for new items added manually) before committing everything to the database, so we don't have to duplicate all the editing and validation capability in the peracotta

**Comment by e-caste** [comment]
@lvps That sounds like a more reasonable approach, yes

**Comment by e-caste** [comment]
Closing since we'll take another approach.
