### ISSUE TITLE
Fix generate_files button in main_with_gui.py

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#29]
The generate button should actually launch the generate_files.sh script with root permissions (at the moment you can run the GUI with `sudo python main_with_gui.py` from the venv).
I've tested it doesn't work at the moment (it doesn't generate any file whatsoever).

**Comment by morpheusthewhite** [comment]
Running gui with root permission in usually discouraged

Gnome also exit with an error when trying to do it

**Comment by lvps** [comment]
@morpheusthewhite I agree but I think this is just a "quick and dirty" fix, the ultimate solution lies in #31... maybe we could do that one first?

**Comment by morpheusthewhite** [comment]
Isn't it the same solution? The difference just lies in the fact the pkexec will provide a graphical interface for inserting root password

**Comment by morpheusthewhite** [comment]
I think the best solution would be to run the interface with user permissions and then require the root password through a simple custom interface when needed (unix root password timeout can be useful in this case). 

I did something similar [here](https://github.com/morpheusthewhite/nordpy/blob/master/bin/root.py)

**Comment by lvps** [comment]
Right, I misread the title... however, we could run the GUI as a normal user, and invoke `pkexec generate_files.sh whatever` (it appears to work), or we could do something similar to your solution

**Comment by morpheusthewhite** [comment]
Yes `pkexec stuff` is good if invoked only one time

**Comment by morpheusthewhite** [comment]
Maybe then https://github.com/WEEE-Open/peracotta/issues/31 should be solved instead of this issue

**Comment by e-caste** [comment]
> Right, I misread the title... however, we could run the GUI as a normal user, and invoke `pkexec generate_files.sh whatever` (it appears to work), or we could do something similar to your solution

@lvps at least for me, it seems _not_ to work. I think it should be installed with `sudo apt install policy-kit1` instead of `sudo apt install pkexec`.
This needs more testing, but just launching `pkexec ./generate_files.sh` crashes, while calling it with `sudo` or `gksu` works perfectly fine.
