### ISSUE TITLE
Change SMART data in read_smartctl.py

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#32]
From `human_readable_smart_data` to simply `smart_data`, which is an enum that can contain the strings "ok", "fail", "old", and something else like "not available" when it's, you guessed it, not available on the disk.
This same info must be displayed in the SMART data section in the GUI instead of the long SMART output found in every `smartctl-dev-sdX.txt` file.

**Comment by lvps** [comment]
Is this done? The code seems to behave as expected

**Comment by e-caste** [comment]
Closing.
