### ISSUE TITLE
Error out if SMART data is disabled

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/peracotta#50]
If it is disabled (not "not supported", this is a different thing) smartctl outputs a specific error message. If that is found, error out and stop until the user enables the SMART data (there's a simple smartctl command to do that).

An even better solution would be to search for that message in extract_data.sh and, if present, send the right command and retry reading the data

**Comment by il-palmi** [comment]
See this https://help.ubuntu.com/community/Smartmontools
