### ISSUE TITLE
Adjust lsblk parameters to support NVME drives

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#53]
Since we currently ignore all the drives that don't start with `/dev/sd`.

This should be done in `generate_files.sh`

**Comment by lvps** [comment]
I suggest searching for a lsblk filter that only lists physical disks (no
partitions, ODDs, etc...), lsblk itself supports some machine-readable
output formats so it should be easy to pipe into something else.

It's also useful to leave a /dev/sd* check as a fallback: lsblk sometimes
doesn't list disks that have failed or haven't been detected correctly, but
smartctl can still probe them (so we can be sure whether they're failed or
just disconnected)

Il mar 10 mar 2020, 12:58 e-caste <notifications@github.com> ha scritto:

**Comment by lvps** [comment]
Copy things from pesto, it does support them
