### ISSUE TITLE
Support new JSON format for Tarallo v2

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#56]
The list of dictionaries should contain the following:
```json
[
{"type": "P", "brand": "ASUS", "model":"P4P800M", "variant": "default", "features": {"vga-ports-n":1, ...}},
{"type": "I", "features":{"sn":"ABC123456",...}}
...
]
```
Where 
- P and I stand for Product and Item, which have been separated in a previous phase
- brand, model and variant are present only if the JSON represents a Product
- features is the dictionary output of the current version of the peracotta

**Comment by lvps** [comment]
Pls also add a way to output this format to the terminal, for the "ad interim" solution (https://github.com/WEEE-Open/tarallo/issues/143)

**Comment by e-caste** [comment]
@mikeus9908 in `extract_data.py` we need:
- [ ] to read the file generated in your previous issue (#60) and _try_ to assign a known manufacturer name to every product and item, if possible (otherwise leave the name that was returned by the parsers)
- [ ] a function  that separates the products from the items (or modify `extract_and_collect_data_from_generated_files` to separate products and items)
- [ ] to modify `extract_data` to return a dict with the newly separated products and items, which will be printed as a JSON in the main

If you need any info on what the tarallo expects to receive see [the wiki](https://github.com/weee-open/tarallo/wiki), in particular the Bulk Add page.  
To try and upload files to the tarallo while solving this issue, please use the **development version** and NOT the production version. You can find details on how to instantiate a tarallo at localhost on [its GitHub page](https://github.com/weee-open/tarallo).

**Comment by lvps** [comment]
In particular, these features (dict keys) should be **both in the item and product**:

- brand
- model
- variant

So when you have a big dict that you split (into item and product features) remember to duplicate them.

These features should appear **only in items** instead, never in products:

- arrival-batch
- cib
- cib-old
- cib-qr
- data-erased
- mac
- notes
- os-license-code
- os-license-version
- other-code
- owner
- smart-data
- sn
- software
- surface-scan
- working
- wwn

Don't worry about their meaning or how to generate them or whatever: if peracotta detects them, you filter them accordingly. If peracotta doesn't detect or doesn't provide them, it doesn't matter.

Every other feature should appear **only in in products**. After all, if you search `ASUS P5VD2-VM` on Google you're going to find how many ports it has, which CPU socket, and so on (product features, it's a motherboard) but not its serial number or MAC address (item features).

Note that the JSON is **not** the same data structure as Item and ItemToUpload and Product and ProductToUpload in pytarallo, this is a special format used for bulk imports from peracotta.
