### ISSUE TITLE
Update GUI to support Tarallo v2 format

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#80]
Some long text (e.g. smartctl's notes) are to be ignored, and some hard to read values still have to be shown both as-is and in a human readable format (e.g. 12GB instead of 1200000000... decibytes).

The most important change though is that the GUI, like the command line version, has to show the items and the products, separated in `extract_data.py`.

**Comment by lvps** [comment]
@e-caste For human readable values, I recommend keeping the int/double value internally, but format a human readable one on the fly and display it.

In tarallo we have functions to do that, both in JS and PHP, which also detect the correct units and all from the feature name: since they are very stable (I literally never changed anything there in years), we could translate them yet again to python and solve all our problems

**Comment by e-caste** [comment]
@lvps Seems like a better way to do it than having unnecessary values in the dictionaries, a solution which I implemented when I was young and naive.

Do you have a link to the code? (Maybe JS is more directly translatable to Python)

**Comment by lvps** [comment]
For the JS version, you need nameToType (feature name to unit symbol):

https://github.com/WEEE-Open/tarallo/blob/6806d2f2d1a6e87fd8032ee2e5bf960984061b25/src/SSRv1/static/editor.js#L471-L493

Then pass that and the raw value to valueToPrintable:

https://github.com/WEEE-Open/tarallo/blob/6806d2f2d1a6e87fd8032ee2e5bf960984061b25/src/SSRv1/static/editor.js#L532-L554

Also you may find something useful in the PHP version which seems to have more stuff but it's not really needed I guess (the JS version can format all the same values exactly in the same way):

https://github.com/WEEE-Open/tarallo/blob/e904905965dffbfbd7c33b352e8ad825ee18f7cd/src/SSRv1/FeaturePrinter.php#L227-L431

Basically, feature names that end with an unit... should be formatted considering that unit.

If you see some comparison with feature types (or "i" or "d")  it doesn't matter, it's just for performance or ease of use, checking the feature name is enough. Also, features in volts and amperes and inches* are double, everything else is integer. That's it.

* If you're curious, they are: diagonal-inch (screen diagonal), psu-12v-rail-ampere (amperes on the 12 V rail of internal PSUs, so we can be sure they support the beefy graphics cards we don't have asd), psu-ampere and psu-volt (for external PSUs). But just check for "-ampere" and similar, not the entire name, as we may add more in the future, even ones that can be detected by the peracotta maybe.

**Comment by e-caste** [comment]
TODO:
1. expand Item (`"type": "I"`) recursively to print all its features
2. expand `"features"` dictionary (recursively if needed) to print its contents

**Comment by lvps** [comment]
Remaining steps as discussed yesterday:

- Use one view for item(s) and one view (?) for products
- Move tables next to each other, instead of one above and one below
- Find a good way to display products (see #104 )
