### ISSUE TITLE
Duplicated products are uploaded twice

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/peracotta#87]
Take a pc with two identical ram sticks. Everything is detected, everything is fine, you create 2 items and 2 products... but the products are exactly identical. Only 1 is needed.

Delete multiple copies of products that have the exact same brand and model (and variant, if provided). Maybe check that, if they have the same brand and model (and variant), all their features are also identical. Check that for products obviously, not for items (it would make no sense and they would have different serials and similar stuff).

**Comment by e-caste** [comment]
This is to fix in `extract_data.py` in `extract_data`
