### ISSUE TITLE
Save/print output in JSON format

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/peracotta#9]
All available features: https://github.com/WEEE-Open/tarallo/blob/master/database-data.sql

* 0 = string
* 1 = integer
* 2 = enum (see FeatureEnum table in same file)
* 3 = double (you won't need it, probably)

Basic structure:
```json
{
	"features": { ... },
	"content": [
		...recursion-here...
	]
}
```

**Comment by e-caste** [comment]
lvps says this issue has been closed
