### ISSUE TITLE
Refactor path concatenation using os.path.join()

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#94]
We are using the common string concatenation (with fstrings, e.g. `f"path/{file}"`, or worse, with plus, e.g. `"path/" + file`) in many places of our codebase. We need to refactor everywhere we see something like this using the appropriate function, e.g. `os.path.join("path", file)` for these 2 reasons:
1. it is safer: no need to worry about slashes
2. it is crossplatform: this is not needed in our case, but it detects if the platform is Windows and uses backslashes instead of forward slashes to concatenate paths

**Comment by PulkitMishra** [comment]
Hey @e-caste I could only find 2 such instances. Please check #95
